source 'https://rubygems.org'

gem "rbvmomi"
gem "trollop"
gem "manageiq-messaging",           :git => "https://github.com/ManageIQ/manageiq-messaging"
gem "manageiq-providers-inventory", :git => "https://github.com/agrare/manageiq-providers-inventory"
